// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { BulkTransaction } from "../response/BulkTransaction";

class BulkCreateTransaction implements Request<BulkTransaction> {
  public readonly __r: BulkTransaction | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    name: string,
    description?: string,
    content: string,
    request_id: string
  };
  public constructor(bodyParams: {
    name: string,
    description?: string,
    content: string,
    request_id: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/transactions" + "/bulk";
  }
}

export { BulkCreateTransaction };
