// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Cashtray } from "../response/Cashtray";

class CancelCashtray implements Request<Cashtray> {
  public readonly __r: Cashtray | undefined;
  public readonly method: Method = "DELETE";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(cashtray_id: string) {
    this.bodyParams = {};
    this.path = "/cashtrays" + "/" + cashtray_id;
  }
}

export { CancelCashtray };
