// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { NIL } from "../response/NIL";

class CaptureCreditSession implements Request<NIL> {
  public readonly __r: NIL | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    session_id: string
  }) {
    if (params.session_id === void 0) throw new Error('"session_id" is required');
    this.path = "/credit-sessions" + "/" + params.session_id + "/capture";
    this.bodyParams = {};
  }
}

export { CaptureCreditSession };
