// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CapturedCreditSession } from "../response/CapturedCreditSession";

class CaptureCreditSession implements Request<CapturedCreditSession> {
  public readonly __r: CapturedCreditSession | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    request_id?: string
  };
  public constructor(params: {
    session_id: string,
    request_id?: string
  }) {
    if (params.session_id === void 0) throw new Error('"session_id" is required');
    this.path = "/credit-sessions" + "/" + params.session_id + "/capture";
    this.bodyParams = {};
    if (params.request_id !== void 0) this.bodyParams.request_id = params.request_id;
  }
}

export { CaptureCreditSession };
