// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { UserCard } from "../response/UserCard";

class CreateCustomerCard implements Request<UserCard> {
  public readonly __r: UserCard | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    token: string,
    is_cardholder_name_specified?: boolean
  };
  public constructor(params: {
    customer_id: string,
    token: string,
    is_cardholder_name_specified?: boolean
  }) {
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    if (params.token === void 0) throw new Error('"token" is required');
    this.path = "/customers" + "/" + params.customer_id + "/cards";
    this.bodyParams = {
      token: params.token,
    };
    if (params.is_cardholder_name_specified !== void 0) this.bodyParams.is_cardholder_name_specified = params.is_cardholder_name_specified;
  }
}

export { CreateCustomerCard };
