// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Transaction } from "../response/Transaction";

class CreateTopupTransactionWithCheck implements Request<Transaction> {
  public readonly __r: Transaction | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    check_id: string,
    customer_id: string
  };
  public constructor(bodyParams: {
    check_id: string,
    customer_id: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/transactions" + "/topup" + "/check";
  }
}

export { CreateTopupTransactionWithCheck };
