// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Transaction } from "../response/Transaction";

class CreateTopupTransaction implements Request<Transaction> {
  public readonly __r: Transaction | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    shop_id: string,
    customer_id: string,
    private_money_id: string,
    bear_point_shop_id?: string,
    money_amount?: number,
    point_amount?: number,
    point_expires_at?: string,
    description?: string
  };
  public constructor(bodyParams: {
    shop_id: string,
    customer_id: string,
    private_money_id: string,
    bear_point_shop_id?: string,
    money_amount?: number,
    point_amount?: number,
    point_expires_at?: string,
    description?: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/transactions" + "/topup";
  }
}

export { CreateTopupTransaction };
