// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Organization } from "../response/Organization";

class CreateOrganization implements Request<Organization> {
  public readonly __r: Organization | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    code: string,
    name: string,
    private_money_ids: string[],
    issuer_admin_user_email: string,
    member_admin_user_email: string,
    bank_name?: string,
    bank_code?: string,
    bank_branch_name?: string,
    bank_branch_code?: string,
    bank_account_type?: string,
    bank_account?: string,
    bank_account_holder_name?: string,
    contact_name?: string
  };
  public constructor(bodyParams: {
    code: string,
    name: string,
    private_money_ids: string[],
    issuer_admin_user_email: string,
    member_admin_user_email: string,
    bank_name?: string,
    bank_code?: string,
    bank_branch_name?: string,
    bank_branch_code?: string,
    bank_account_type?: string,
    bank_account?: string,
    bank_account_holder_name?: string,
    contact_name?: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/organizations";
  }
}

export { CreateOrganization };
