// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CvsAuthorization } from "../response/CvsAuthorization";

class CreateCvsAuthorization implements Request<CvsAuthorization> {
  public readonly __r: CvsAuthorization | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    customer_id: string,
    receiver_user_id?: string,
    private_money_id: string,
    amount: number,
    service_option_type: string,
    name1: string,
    name2: string,
    tel: string,
    topup_quota_id?: number
  };
  public constructor(params: {
    customer_id: string,
    receiver_user_id?: string,
    private_money_id: string,
    amount: number,
    service_option_type: string,
    name1: string,
    name2: string,
    tel: string,
    topup_quota_id?: number
  }) {
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    if (params.amount === void 0) throw new Error('"amount" is required');
    if (params.service_option_type === void 0) throw new Error('"service_option_type" is required');
    if (params.name1 === void 0) throw new Error('"name1" is required');
    if (params.name2 === void 0) throw new Error('"name2" is required');
    if (params.tel === void 0) throw new Error('"tel" is required');
    this.path = "/cvs";
    this.bodyParams = {
      customer_id: params.customer_id,
      private_money_id: params.private_money_id,
      amount: params.amount,
      service_option_type: params.service_option_type,
      name1: params.name1,
      name2: params.name2,
      tel: params.tel,
    };
    if (params.receiver_user_id !== void 0) this.bodyParams.receiver_user_id = params.receiver_user_id;
    if (params.topup_quota_id !== void 0) this.bodyParams.topup_quota_id = params.topup_quota_id;
  }
}

export { CreateCvsAuthorization };
