// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Transaction } from "../response/Transaction";

class CreateTransferTransaction implements Request<Transaction> {
  public readonly __r: Transaction | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    sender_id: string,
    receiver_id: string,
    private_money_id: string,
    amount: number,
    description?: string
  };
  public constructor(bodyParams: {
    sender_id: string,
    receiver_id: string,
    private_money_id: string,
    amount: number,
    description?: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/transactions" + "/transfer";
  }
}

export { CreateTransferTransaction };
