// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionGroup } from "../response/TransactionGroup";

class CreateTransactionGroup implements Request<TransactionGroup> {
  public readonly __r: TransactionGroup | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    name: string
  };
  public constructor(params: {
    name: string
  }) {
    if (params.name === void 0) throw new Error('"name" is required');
    this.path = "/transaction-groups";
    this.bodyParams = {
      name: params.name,
    };
  }
}

export { CreateTransactionGroup };
