// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionDetail } from "../response/TransactionDetail";

class CreateTransactionWithCashtray implements Request<TransactionDetail> {
  public readonly __r: TransactionDetail | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    cashtray_id: string,
    customer_id: string,
    strategy?: string,
    request_id?: string
  };
  public constructor(params: {
    cashtray_id: string,
    customer_id: string,
    strategy?: string,
    request_id?: string
  }) {
    if (params.cashtray_id === void 0) throw new Error('"cashtray_id" is required');
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    this.path = "/transactions" + "/cashtray";
    this.bodyParams = {
      cashtray_id: params.cashtray_id,
      customer_id: params.customer_id,
    };
    if (params.strategy !== void 0) this.bodyParams.strategy = params.strategy;
    if (params.request_id !== void 0) this.bodyParams.request_id = params.request_id;
  }
}

export { CreateTransactionWithCashtray };
