// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionDetail } from "../response/TransactionDetail";

class CreatePaymentTransactionWithBill implements Request<TransactionDetail> {
  public readonly __r: TransactionDetail | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    bill_id: string,
    customer_id: string,
    metadata?: string,
    request_id?: string,
    strategy?: string
  };
  public constructor(params: {
    bill_id: string,
    customer_id: string,
    metadata?: string,
    request_id?: string,
    strategy?: string
  }) {
    if (params.bill_id === void 0) throw new Error('"bill_id" is required');
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    this.path = "/transactions" + "/payment" + "/bill";
    this.bodyParams = {
      bill_id: params.bill_id,
      customer_id: params.customer_id,
    };
    if (params.metadata !== void 0) this.bodyParams.metadata = params.metadata;
    if (params.request_id !== void 0) this.bodyParams.request_id = params.request_id;
    if (params.strategy !== void 0) this.bodyParams.strategy = params.strategy;
  }
}

export { CreatePaymentTransactionWithBill };
