// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Transaction } from "../response/Transaction";

class CreateExchangeTransaction implements Request<Transaction> {
  public readonly __r: Transaction | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    user_id: string,
    sender_private_money_id: string,
    receiver_private_money_id: string,
    amount: number,
    description?: string
  };
  public constructor(bodyParams: {
    user_id: string,
    sender_private_money_id: string,
    receiver_private_money_id: string,
    amount: number,
    description?: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/transactions" + "/exchange";
  }
}

export { CreateExchangeTransaction };
