// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { BillWithAdditionalPrivateMoneys } from "../response/BillWithAdditionalPrivateMoneys";

class CreateBill implements Request<BillWithAdditionalPrivateMoneys> {
  public readonly __r: BillWithAdditionalPrivateMoneys | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    amount?: number,
    private_money_id: string,
    additional_private_money_ids?: string[],
    shop_id: string,
    description?: string
  };
  public constructor(params: {
    amount?: number,
    private_money_id: string,
    additional_private_money_ids?: string[],
    shop_id: string,
    description?: string
  }) {
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    if (params.shop_id === void 0) throw new Error('"shop_id" is required');
    this.path = "/bills";
    this.bodyParams = {
      private_money_id: params.private_money_id,
      shop_id: params.shop_id,
    };
    if (params.amount !== void 0) this.bodyParams.amount = params.amount;
    if (params.additional_private_money_ids !== void 0) this.bodyParams.additional_private_money_ids = params.additional_private_money_ids;
    if (params.description !== void 0) this.bodyParams.description = params.description;
  }
}

export { CreateBill };
