// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CreditSessionTransactionResult } from "../response/CreditSessionTransactionResult";

class CreateCreditSessionTransaction implements Request<CreditSessionTransactionResult> {
  public readonly __r: CreditSessionTransactionResult | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    amount: number,
    shop_id?: string,
    description?: string,
    request_id?: string
  };
  public constructor(params: {
    session_id: string,
    amount: number,
    shop_id?: string,
    description?: string,
    request_id?: string
  }) {
    if (params.session_id === void 0) throw new Error('"session_id" is required');
    if (params.amount === void 0) throw new Error('"amount" is required');
    this.path = "/credit-sessions" + "/" + params.session_id + "/transactions";
    this.bodyParams = {
      amount: params.amount,
    };
    if (params.shop_id !== void 0) this.bodyParams.shop_id = params.shop_id;
    if (params.description !== void 0) this.bodyParams.description = params.description;
    if (params.request_id !== void 0) this.bodyParams.request_id = params.request_id;
  }
}

export { CreateCreditSessionTransaction };
