// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { User } from "../response/User";

class CreateShop implements Request<User> {
  public readonly __r: User | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    shop_name: string,
    shop_postal_code?: string,
    shop_address?: string,
    shop_tel?: string,
    shop_email?: string,
    shop_external_id?: string,
    organization_code?: string
  };
  public constructor(bodyParams: {
    shop_name: string,
    shop_postal_code?: string,
    shop_address?: string,
    shop_tel?: string,
    shop_email?: string,
    shop_external_id?: string,
    organization_code?: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/shops";
  }
}

export { CreateShop };
