// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Cashtray } from "../response/Cashtray";

class CreateCashtray implements Request<Cashtray> {
  public readonly __r: Cashtray | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id: string,
    shop_id: string,
    amount: number,
    description?: string,
    expires_in?: number
  };
  public constructor(bodyParams: {
    private_money_id: string,
    shop_id: string,
    amount: number,
    description?: string,
    expires_in?: number
  }) {
    this.bodyParams = bodyParams;
    this.path = "/cashtrays";
  }
}

export { CreateCashtray };
