// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Check } from "../response/Check";

class CreateCheck implements Request<Check> {
  public readonly __r: Check | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    money_amount?: number,
    point_amount?: number,
    account_id: string,
    description?: string,
    is_onetime?: boolean,
    usage_limit?: number,
    expires_at?: string,
    point_expires_at?: string,
    point_expires_in_days?: number,
    bear_point_account?: string
  };
  public constructor(bodyParams: {
    money_amount?: number,
    point_amount?: number,
    account_id: string,
    description?: string,
    is_onetime?: boolean,
    usage_limit?: number,
    expires_at?: string,
    point_expires_at?: string,
    point_expires_in_days?: number,
    bear_point_account?: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/checks";
  }
}

export { CreateCheck };
