// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CardAuthorizeResult } from "../response/CardAuthorizeResult";

class CreditCardTopupWithMdkToken implements Request<CardAuthorizeResult> {
  public readonly __r: CardAuthorizeResult | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    token: string,
    private_money_id: string,
    receiver_user_id?: string,
    amount: number,
    is_cardholder_name_specified?: boolean,
    request_id?: string,
    topup_quota_id?: number
  };
  public constructor(params: {
    customer_id: string,
    token: string,
    private_money_id: string,
    receiver_user_id?: string,
    amount: number,
    is_cardholder_name_specified?: boolean,
    request_id?: string,
    topup_quota_id?: number
  }) {
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    if (params.token === void 0) throw new Error('"token" is required');
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    if (params.amount === void 0) throw new Error('"amount" is required');
    this.path = "/customers" + "/" + params.customer_id + "/card-authorize" + "/topup-with-mdk-token";
    this.bodyParams = {
      token: params.token,
      private_money_id: params.private_money_id,
      amount: params.amount,
    };
    if (params.receiver_user_id !== void 0) this.bodyParams.receiver_user_id = params.receiver_user_id;
    if (params.is_cardholder_name_specified !== void 0) this.bodyParams.is_cardholder_name_specified = params.is_cardholder_name_specified;
    if (params.request_id !== void 0) this.bodyParams.request_id = params.request_id;
    if (params.topup_quota_id !== void 0) this.bodyParams.topup_quota_id = params.topup_quota_id;
  }
}

export { CreditCardTopupWithMdkToken };
