// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CustomerCardDeleted } from "../response/CustomerCardDeleted";

class DeleteCustomerCard implements Request<CustomerCardDeleted> {
  public readonly __r: CustomerCardDeleted | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    card_uuid: string
  };
  public constructor(params: {
    customer_id: string,
    card_uuid: string
  }) {
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    if (params.card_uuid === void 0) throw new Error('"card_uuid" is required');
    this.path = "/customers" + "/" + params.customer_id + "/cards" + "/delete";
    this.bodyParams = {
      card_uuid: params.card_uuid,
    };
  }
}

export { DeleteCustomerCard };
