// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { AccountDetail } from "../response/AccountDetail";

class GetAccount implements Request<AccountDetail> {
  public readonly __r: AccountDetail | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(account_id: string) {
    this.bodyParams = {};
    this.path = "/accounts" + "/" + account_id;
  }
}

export { GetAccount };
