// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { BulkTransaction } from "../response/BulkTransaction";

class GetBulkTransaction implements Request<BulkTransaction> {
  public readonly __r: BulkTransaction | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(bulk_transaction_id: string) {
    this.bodyParams = {};
    this.path = "/bulk-transactions" + "/" + bulk_transaction_id;
  }
}

export { GetBulkTransaction };
