// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { BillWithAdditionalPrivateMoneys } from "../response/BillWithAdditionalPrivateMoneys";

class GetBill implements Request<BillWithAdditionalPrivateMoneys> {
  public readonly __r: BillWithAdditionalPrivateMoneys | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    bill_id: string
  }) {
    if (params.bill_id === void 0) throw new Error('"bill_id" is required');
    this.path = "/bills" + "/" + params.bill_id;
    this.bodyParams = {};
  }
}

export { GetBill };
