// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CashtrayWithResult } from "../response/CashtrayWithResult";

class GetCashtray implements Request<CashtrayWithResult> {
  public readonly __r: CashtrayWithResult | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(cashtray_id: string) {
    this.bodyParams = {};
    this.path = "/cashtrays" + "/" + cashtray_id;
  }
}

export { GetCashtray };
