// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedUserCards } from "../response/PaginatedUserCards";

class GetCustomerCards implements Request<PaginatedUserCards> {
  public readonly __r: PaginatedUserCards | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    page?: number,
    per_page?: number
  };
  public constructor(params: {
    customer_id: string,
    page?: number,
    per_page?: number
  }) {
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    this.path = "/customers" + "/" + params.customer_id + "/cards";
    this.bodyParams = {};
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { GetCustomerCards };
