// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedCustomers } from "../response/PaginatedCustomers";

class GetCustomer implements Request<PaginatedCustomers> {
  public readonly __r: PaginatedCustomers | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params?: {}) {
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    this.path = "/customers";
    this.bodyParams = {};
    if (params === void 0) return;
    if (params.customer_id !== void 0) this.bodyParams.customer_id = params.customer_id;
    if (params.customer_name !== void 0) this.bodyParams.customer_name = params.customer_name;
    if (params.customer_tel !== void 0) this.bodyParams.customer_tel = params.customer_tel;
    if (params.customer_email !== void 0) this.bodyParams.customer_email = params.customer_email;
    if (params.account_status !== void 0) this.bodyParams.account_status = params.account_status;
    if (params.registered_from !== void 0) this.bodyParams.registered_from = params.registered_from;
    if (params.registered_to !== void 0) this.bodyParams.registered_to = params.registered_to;
    if (params.last_transaction_from !== void 0) this.bodyParams.last_transaction_from = params.last_transaction_from;
    if (params.last_transaction_to !== void 0) this.bodyParams.last_transaction_to = params.last_transaction_to;
    if (params.individual_number_identification !== void 0) this.bodyParams.individual_number_identification = params.individual_number_identification;
    if (params.resident_status !== void 0) this.bodyParams.resident_status = params.resident_status;
    if (params.is_include_user_attribute !== void 0) this.bodyParams.is_include_user_attribute = params.is_include_user_attribute;
    if (params.external_id !== void 0) this.bodyParams.external_id = params.external_id;
    if (params.with_balance !== void 0) this.bodyParams.with_balance = params.with_balance;
    if (params.sort_by !== void 0) this.bodyParams.sort_by = params.sort_by;
    if (params.sort_direction !== void 0) this.bodyParams.sort_direction = params.sort_direction;
    if (params.page !== void 0) this.bodyParams.page = params.page;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { GetCustomer };
