// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CvsAuthorization } from "../response/CvsAuthorization";

class GetCvsAuthorization implements Request<CvsAuthorization> {
  public readonly __r: CvsAuthorization | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    order_id: string
  }) {
    if (params.order_id === void 0) throw new Error('"order_id" is required');
    this.path = "/cvs" + "/" + params.order_id;
    this.bodyParams = {};
  }
}

export { GetCvsAuthorization };
