// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedCvsAuthorizations } from "../response/PaginatedCvsAuthorizations";

class GetCvsAuthorizations implements Request<PaginatedCvsAuthorizations> {
  public readonly __r: PaginatedCvsAuthorizations | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id: string,
    customer_id?: string,
    status?: string,
    before?: string,
    after?: string,
    per_page?: number
  };
  public constructor(params: {
    private_money_id: string,
    customer_id?: string,
    status?: string,
    before?: string,
    after?: string,
    per_page?: number
  }) {
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    this.path = "/cvs";
    this.bodyParams = {
      private_money_id: params.private_money_id,
    };
    if (params.customer_id !== void 0) this.bodyParams.customer_id = params.customer_id;
    if (params.status !== void 0) this.bodyParams.status = params.status;
    if (params.before !== void 0) this.bodyParams.before = params.before;
    if (params.after !== void 0) this.bodyParams.after = params.after;
    if (params.per_page !== void 0) this.bodyParams.per_page = params.per_page;
  }
}

export { GetCvsAuthorizations };
