// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedPrivateMoneys } from "../response/PaginatedPrivateMoneys";

class GetPrivateMoneys implements Request<PaginatedPrivateMoneys> {
  public readonly __r: PaginatedPrivateMoneys | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    organization_code?: string,
    page?: number,
    per_page?: number
  };
  public constructor(bodyParams?: {
    organization_code?: string,
    page?: number,
    per_page?: number
  }) {
    this.bodyParams = bodyParams ?? {};
    this.path = "/private-moneys";
  }
}

export { GetPrivateMoneys };
