// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { SevenBankATMSession } from "../response/SevenBankATMSession";

class GetSevenBankATMSession implements Request<SevenBankATMSession> {
  public readonly __r: SevenBankATMSession | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    qr_info: string
  }) {
    if (params.qr_info === void 0) throw new Error('"qr_info" is required');
    this.path = "/seven-bank-atm-sessions" + "/" + params.qr_info;
    this.bodyParams = {};
  }
}

export { GetSevenBankATMSession };
