// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Transaction } from "../response/Transaction";

class GetTransaction implements Request<Transaction> {
  public readonly __r: Transaction | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    transaction_id: string
  }) {
    if (params.transaction_id === void 0) throw new Error('"transaction_id" is required');
    this.path = "/transactions" + "/" + params.transaction_id;
    this.bodyParams = {};
  }
}

export { GetTransaction };
