// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Transaction } from "../response/Transaction";

class GetTransaction implements Request<Transaction> {
  public readonly __r: Transaction | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(transaction_id: string) {
    this.bodyParams = {};
    this.path = "/transactions" + "/" + transaction_id;
  }
}

export { GetTransaction };
