// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedBills } from "../response/PaginatedBills";

class ListBills implements Request<PaginatedBills> {
  public readonly __r: PaginatedBills | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    page?: number,
    per_page?: number,
    bill_id?: string,
    private_money_id?: string,
    organization_code?: string,
    description?: string,
    created_from?: string,
    created_to?: string,
    shop_name?: string,
    shop_id?: string,
    lower_limit_amount?: number,
    upper_limit_amount?: number,
    is_disabled?: boolean
  };
  public constructor(bodyParams?: {
    page?: number,
    per_page?: number,
    bill_id?: string,
    private_money_id?: string,
    organization_code?: string,
    description?: string,
    created_from?: string,
    created_to?: string,
    shop_name?: string,
    shop_id?: string,
    lower_limit_amount?: number,
    upper_limit_amount?: number,
    is_disabled?: boolean
  }) {
    this.bodyParams = bodyParams ?? {};
    this.path = "/bills";
  }
}

export { ListBills };
