// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedShops } from "../response/PaginatedShops";

class ListShops implements Request<PaginatedShops> {
  public readonly __r: PaginatedShops | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    organization_code?: string,
    private_money_id?: string,
    name?: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    page?: number,
    per_page?: number
  };
  public constructor(bodyParams?: {
    organization_code?: string,
    private_money_id?: string,
    name?: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    page?: number,
    per_page?: number
  }) {
    this.bodyParams = bodyParams ?? {};
    this.path = "/shops";
  }
}

export { ListShops };
