// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedAccounts } from "../response/PaginatedAccounts";

class ListUserAccounts implements Request<PaginatedAccounts> {
  public readonly __r: PaginatedAccounts | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    user_id: string
  }) {
    if (params.user_id === void 0) throw new Error('"user_id" is required');
    this.path = "/users" + "/" + params.user_id + "/accounts";
    this.bodyParams = {};
  }
}

export { ListUserAccounts };
