// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { PaginatedTransaction } from "../response/PaginatedTransaction";

class ListCustomerTransactions implements Request<PaginatedTransaction> {
  public readonly __r: PaginatedTransaction | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {
    private_money_id: string,
    sender_customer_id?: string,
    receiver_customer_id?: string,
    type?: string,
    is_modified?: boolean,
    from?: string,
    to?: string,
    page?: number,
    per_page?: number
  };
  public constructor(bodyParams: {
    private_money_id: string,
    sender_customer_id?: string,
    receiver_customer_id?: string,
    type?: string,
    is_modified?: boolean,
    from?: string,
    to?: string,
    page?: number,
    per_page?: number
  }) {
    this.bodyParams = bodyParams;
    this.path = "/customers" + "/transactions";
  }
}

export { ListCustomerTransactions };
