// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { CreditSession } from "../response/CreditSession";

class PostCreditSession implements Request<CreditSession> {
  public readonly __r: CreditSession | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    customer_id: string,
    private_money_id: string,
    card_id: string,
    expires_at: string
  };
  public constructor(params: {
    customer_id: string,
    private_money_id: string,
    card_id: string,
    expires_at: string
  }) {
    if (params.customer_id === void 0) throw new Error('"customer_id" is required');
    if (params.private_money_id === void 0) throw new Error('"private_money_id" is required');
    if (params.card_id === void 0) throw new Error('"card_id" is required');
    if (params.expires_at === void 0) throw new Error('"expires_at" is required');
    this.path = "/credit-sessions";
    this.bodyParams = {
      customer_id: params.customer_id,
      private_money_id: params.private_money_id,
      card_id: params.card_id,
      expires_at: params.expires_at,
    };
  }
}

export { PostCreditSession };
