// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Transfer } from "../response/Transfer";

class RefundTransaction implements Request<Transfer> {
  public readonly __r: Transfer | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    description?: string
  };
  public constructor(transaction_id: string, bodyParams?: {
    description?: string
  }) {
    this.bodyParams = bodyParams ?? {};
    this.path = "/transactions" + "/" + transaction_id + "/refund";
  }
}

export { RefundTransaction };
