// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Echo } from "../response/Echo";

class SendEcho implements Request<Echo> {
  public readonly __r: Echo | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    message: string
  };
  public constructor(bodyParams: {
    message: string
  }) {
    this.bodyParams = bodyParams;
    this.path = "/echo";
  }
}

export { SendEcho };
