// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { TransactionGroup } from "../response/TransactionGroup";

class ShowTransactionGroup implements Request<TransactionGroup> {
  public readonly __r: TransactionGroup | undefined;
  public readonly method: Method = "GET";
  public readonly path: string;
  public readonly bodyParams: {};
  public constructor(params: {
    uuid: string
  }) {
    if (params.uuid === void 0) throw new Error('"uuid" is required');
    this.path = "/transaction-groups" + "/" + params.uuid;
    this.bodyParams = {};
  }
}

export { ShowTransactionGroup };
