// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { UserStatsOperation } from "../response/UserStatsOperation";

class TerminateUserStats implements Request<UserStatsOperation> {
  public readonly __r: UserStatsOperation | undefined;
  public readonly method: Method = "POST";
  public readonly path: string;
  public readonly bodyParams: {
    operation_id: string
  };
  public constructor(params: {
    operation_id: string
  }) {
    if (params.operation_id === void 0) throw new Error('"operation_id" is required');
    this.path = "/user-stats" + "/terminate";
    this.bodyParams = {
      operation_id: params.operation_id,
    };
  }
}

export { TerminateUserStats };
