// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { ShopWithAccounts } from "../response/ShopWithAccounts";

class UpdateShop implements Request<ShopWithAccounts> {
  public readonly __r: ShopWithAccounts | undefined;
  public readonly method: Method = "PATCH";
  public readonly path: string;
  public readonly bodyParams: {
    name?: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    private_money_ids?: string[],
    can_topup_private_money_ids?: string[]
  };
  public constructor(shop_id: string, bodyParams: {
    name?: string,
    postal_code?: string,
    address?: string,
    tel?: string,
    email?: string,
    external_id?: string,
    private_money_ids?: string[],
    can_topup_private_money_ids?: string[]
  }) {
    this.bodyParams = bodyParams;
    this.path = "/shops" + "/" + shop_id;
  }
}

export { UpdateShop };
