// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Bill } from "../response/Bill";

class UpdateBill implements Request<Bill> {
  public readonly __r: Bill | undefined;
  public readonly method: Method = "PATCH";
  public readonly path: string;
  public readonly bodyParams: {
    amount?: number,
    description?: string,
    is_disabled?: boolean
  };
  public constructor(bill_id: string, bodyParams: {
    amount?: number,
    description?: string,
    is_disabled?: boolean
  }) {
    this.bodyParams = bodyParams;
    this.path = "/bills" + "/" + bill_id;
  }
}

export { UpdateBill };
