// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { AccountDetail } from "../response/AccountDetail";

class UpdateAccount implements Request<AccountDetail> {
  public readonly __r: AccountDetail | undefined;
  public readonly method: Method = "PATCH";
  public readonly path: string;
  public readonly bodyParams: {
    is_suspended?: boolean
  };
  public constructor(account_id: string, bodyParams: {
    is_suspended?: boolean
  }) {
    this.bodyParams = bodyParams;
    this.path = "/accounts" + "/" + account_id;
  }
}

export { UpdateAccount };
