// DO NOT EDIT: File is generated by code generator.

import { Request, Method } from "./Request";
import { Cashtray } from "../response/Cashtray";

class UpdateCashtray implements Request<Cashtray> {
  public readonly __r: Cashtray | undefined;
  public readonly method: Method = "PATCH";
  public readonly path: string;
  public readonly bodyParams: {
    amount?: number,
    description?: string,
    expires_in?: number
  };
  public constructor(cashtray_id: string, bodyParams: {
    amount?: number,
    description?: string,
    expires_in?: number
  }) {
    this.bodyParams = bodyParams;
    this.path = "/cashtrays" + "/" + cashtray_id;
  }
}

export { UpdateCashtray };
