// DO NOT EDIT: File is generated by code generator.

import { AccountStatus } from "./AccountStatus";
import { PrivateMoney } from "./PrivateMoney";
import { User } from "./User";

interface AccountDetail {
  readonly id: string;
  readonly name: string;
  readonly is_suspended: boolean;
  readonly status: AccountStatus;
  readonly balance: number;
  readonly money_balance: number;
  readonly point_balance: number;
  readonly private_money: PrivateMoney;
  readonly user: User;
}

export { AccountDetail };
