// DO NOT EDIT: File is generated by code generator.

import { Transaction } from "./Transaction";
import { Bill } from "./Bill";

interface BillTransaction {
  readonly transaction: Transaction;
  readonly bill: Bill;
}

export { BillTransaction };
