// DO NOT EDIT: File is generated by code generator.

interface CampaignShopLabelUserTagGroup {
  readonly id: string;
  readonly name_en: string;
  readonly name_ja: string;
}

export { CampaignShopLabelUserTagGroup };
