// DO NOT EDIT: File is generated by code generator.

import { CampaignShopLabelUserTagGroup } from "./CampaignShopLabelUserTagGroup";

interface CampaignShopLabel {
  readonly id: string;
  readonly name_en: string;
  readonly name_ja: string;
  readonly user_tag_group: CampaignShopLabelUserTagGroup;
}

export { CampaignShopLabel };
