// DO NOT EDIT: File is generated by code generator.

import { IndividualNumberIdentification } from "./IndividualNumberIdentification";

interface CustomerListRow {
  readonly id: string;
  readonly name: string;
  readonly tel: string;
  readonly email: string;
  readonly registered_at: string;
  readonly last_transaction_done_at?: string;
  readonly money_balance?: number;
  readonly point_balance?: number;
  readonly account_uuid: string;
  readonly account_is_suspended: boolean;
  readonly account_status: string;
  readonly external_id?: string;
  readonly individual_number_identification: IndividualNumberIdentification;
}

export { CustomerListRow };
