// DO NOT EDIT: File is generated by code generator.

import { AccountDetail } from "./AccountDetail";
import { User } from "./User";

interface CvsAuthorization {
  readonly account: AccountDetail;
  readonly user: User;
  readonly order_id: string;
  readonly transaction_id?: string;
  readonly pay_limit: string;
  readonly tel: string;
  readonly name1: string;
  readonly name2: string;
  readonly amount: number;
  readonly service_option_type: string;
  readonly haraikomi_url: string;
  readonly receipt_no: string;
  readonly done_at?: string;
  readonly canceled_at?: string;
}

export { CvsAuthorization };
