// DO NOT EDIT: File is generated by code generator.

interface IndividualNumberIdentification {
  readonly is_identified: boolean;
  readonly last_identified_at?: string;
  readonly expires_at?: string;
  readonly is_resident?: boolean;
}

export { IndividualNumberIdentification };
