// DO NOT EDIT: File is generated by code generator.

import { Object } from "./Object"

interface InvalidParameters {
  readonly type: string;
  readonly message: string;
  readonly errors: Object;
}

export { InvalidParameters };
