// DO NOT EDIT: File is generated by code generator.

import { CustomerListRow } from "./CustomerListRow";
import { Pagination } from "./Pagination";

interface PaginatedCustomers {
  readonly rows: CustomerListRow[];
  readonly count: number;
  readonly pagination: Pagination;
}

export { PaginatedCustomers };
