// DO NOT EDIT: File is generated by code generator.

import { UserCard } from "./UserCard";
import { Pagination } from "./Pagination";

interface PaginatedUserCards {
  readonly rows: UserCard[];
  readonly count: number;
  readonly pagination: Pagination;
}

export { PaginatedUserCards };
