// DO NOT EDIT: File is generated by code generator.

import { BillTransaction } from "./BillTransaction";

interface PaginatedBillTransaction {
  readonly rows: BillTransaction[];
  readonly per_page: number;
  readonly count: number;
  readonly next_page_cursor_id?: string;
  readonly prev_page_cursor_id?: string;
}

export { PaginatedBillTransaction };
