// DO NOT EDIT: File is generated by code generator.

import { CvsAuthorization } from "./CvsAuthorization";

interface PaginatedCvsAuthorizations {
  readonly per_page: number;
  readonly count: number;
  readonly items: CvsAuthorization[];
  readonly prev?: string;
  readonly next?: string;
}

export { PaginatedCvsAuthorizations };
