// DO NOT EDIT: File is generated by code generator.

import { AccountDetail } from "./AccountDetail";
import { Transaction } from "./Transaction";

interface SevenBankATMSession {
  readonly qr_info: string;
  readonly account: AccountDetail;
  readonly amount: number;
  readonly transaction?: Transaction;
  readonly seven_bank_customer_number: string;
  readonly atm_id?: string;
  readonly audi_id?: string;
  readonly issuer_code?: string;
  readonly issuer_name?: string;
  readonly money_name?: string;
}

export { SevenBankATMSession };
