// DO NOT EDIT: File is generated by code generator.

import { Transaction } from "./Transaction";

interface TransactionGroup {
  readonly id: string;
  readonly name: string;
  readonly created_at: string;
  readonly updated_at: string;
  readonly transactions: Transaction[];
}

export { TransactionGroup };
